manifest:
  remotes:
    - name: harlord
      url-base: https://github.com/harlord
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware

    - name: inorichi
      url-base: https://github.com/inorichi
  projects:
    - name: zmk
      remote: harlord
      revision: main-local2
      import: app/west.yml
      
    - name: zmk-pmw3610-driver
      remote: inorichi
      revision: main
  self:
    path: config